### ISSUE TITLE
Time How long Pi-hole will be disabled set in homekit

### ISSUE THREAD

**Issue by Nastras** [arendruni/homebridge-pihole#10]
Hello, would it be possible that you include a way to set the time for disable in HomeKit?

There is a plugin that seems to have this feature but can't be installed. Maybe you can use some of the code?
https://github.com/thkl/homebridge-piholeOff

Would be cool if you can implement this function.

Thanks!

Many greetings

Nastras

**Comment by arendruni** [comment]
Maybe in the future I’ll try to integrate those features.
