### ISSUE TITLE
[BUG] changes have no effect to Pi-hole

### ISSUE THREAD

**Issue by F3000** [arendruni/homebridge-pihole#12]
**Describe the bug**
the HomeKit switch has no function to the backend 

**To Reproduce**

I press the switch . Only the color of the button changes .

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

The plugin in installed via HOOBS for Homebridge

**Comment by arendruni** [comment]
Hi @F3000, could you please add some homebridge logs to this issue? Before doing so make sure to correctly configure the `"logLevel": 2` in you config.json file.

**Comment by Spy-1** [comment]
same here

**Comment by freddair** [comment]
same here... here is a log (auth key xx'ed out):

14.6.2020, 20:17:40 [Pi-hole 5 Minuten aus] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"content-type":"application/json","set-cookie":["PHPSESSID=b4sl3banf85inbqfd95glboouv; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"21","connection":"close","date":"Sun, 14 Jun 2020 18:17:40 GMT","server":"lighttpd/1.4.53"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://localhost:1882/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
14.6.2020, 20:17:49 [Pi-hole 5 Minuten aus] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"content-type":"application/json","set-cookie":["PHPSESSID=63vchh69jof4jors5do3tt932o; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"21","connection":"close","date":"Sun, 14 Jun 2020 18:17:49 GMT","server":"lighttpd/1.4.53"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://localhost:1882/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
14.6.2020, 20:17:50 [Pi-hole 5 Minuten aus] {"data":{"status":"enabled"},"status":200,"statusText":"OK","headers":{"content-type":"application/json","set-cookie":["PHPSESSID=v3nq4sj06cu8rns05haa7h1r1s; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"20","connection":"close","date":"Sun, 14 Jun 2020 18:17:50 GMT","server":"lighttpd/1.4.53"},"request":{"url":"api.php","method":"get","params":{"enable":1,"auth":"xxx"},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://localhost:1882/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
14.6.2020, 20:17:57 [Pi-hole 5 Minuten aus] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"content-type":"application/json","set-cookie":["PHPSESSID=hi6hl1toufn2l4k2aradvi0t1s; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"21","connection":"close","date":"Sun, 14 Jun 2020 18:17:57 GMT","server":"lighttpd/1.4.53"},"request":{"url":"api.php","method":"get","params":{"disable":300,"auth":"xxx"},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://localhost:1882/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

**Comment by arendruni** [comment]
I don’t see anything wrong in the response output. 
What’s the status on your Pi-hole admin after disabling it from the plugin?

**Comment by freddair** [comment]
![image](https://user-images.githubusercontent.com/63143560/84602064-14bc7580-ae85-11ea-87fd-d8be4d7f9fcc.jpeg)![image](https://user-images.githubusercontent.com/63143560/84602068-18e89300-ae85-11ea-8b4f-82c64fb9d3e4.jpeg)

**Comment by freddair** [comment]
What I find a bit strange:

"expires":"Thu, 19 Nov 1981

**Comment by arendruni** [comment]
> What I find a bit strange:
> 
> "expires":"Thu, 19 Nov 1981

That’s a standard value, I have it too

**Comment by arendruni** [comment]
Have you tried making a manual request using curl?

**Comment by freddair** [comment]
Wouldn’t know how.

**Comment by arendruni** [comment]
Try with these:

```
curl -X GET -v "http://HOSTNAME:PORT/admin/api.php?disable&auth=AUTH_TOKEN"
```
to disable Pi-hole

```
curl -X GET -v "http://HOSTNAME:PORT/admin/api.php?enable&auth=AUTH_TOKEN"
```
to enable Pi-hole, and

```
curl -X GET -v "http://HOSTNAME:PORT/admin/api.php?status"
```
to get the status.

**Comment by freddair** [comment]
Thanks. Now that is strange. The status via curl: {"status":"disabled"}. Via Terminal „pinhole Status“: enabled. Via Admin Web-GUI: Status unknown. What’s going on?![image](https://user-images.githubusercontent.com/63143560/84603258-52250100-ae8d-11ea-8639-665130bf9f18.jpeg)![image](https://user-images.githubusercontent.com/63143560/84603262-57824b80-ae8d-11ea-89ad-f10883340b7c.jpeg)![image](https://user-images.githubusercontent.com/63143560/84603264-5bae6900-ae8d-11ea-9a44-6ecb9bef7a26.jpeg)

**Comment by freddair** [comment]
those status do not change no matter how the switch is set...

**Comment by arendruni** [comment]
Which version of Pi-hole do you have?

**Comment by freddair** [comment]
v5.0 installed via HOOBS Script:

https://support.hoobs.org/docs/5e875a0e0ab68b0344e872c3

**Comment by arendruni** [comment]
I believe that the problem is with Pi-hole installed in Hoobs, but I need to install it to the the plugin. 
Which version of Hoobs do you have?

**Comment by freddair** [comment]
3.2.6

**Comment by arendruni** [comment]
So, I installed Hoobs on my Raspberry 4 and everything works like it should.

**Comment by F3000** [comment]
> I believe that the problem is with Pi-hole installed in Hoobs, but I need to install it to the the plugin. 
> 
> Which version of Hoobs do you have?

The Hoobs installer download the standard pi hole and install them. 
After that the script execute some additional code to change the port of pi hole

**Comment by freddair** [comment]
So it should work but it does not.

**Comment by arendruni** [comment]
There’s a version of the plugin that works?

**Comment by arendruni** [comment]
Do you still have this problem?

@F3000 @freddair

**Comment by F3000** [comment]
> Do you still have this problem?
> 
> 
> 
> @F3000 @freddair 

Hi , no I don't have problems anymore

**Comment by freddair** [comment]
Hadn't used it since then. Reinstalled it and seems to work for me now. Thanks!
