### ISSUE TITLE
Switch does not display the right status

### ISSUE THREAD

**Issue by Damien514** [arendruni/homebridge-pihole#13]
Is there a way to get the switch display the status of the PiHole? If I turn off PiHole for 1 minute, the "switch" still display "On" after this delay.

**Comment by arendruni** [comment]
Hi @Damien514 thanks for the issue
Did you disable pi-hole from the admin page? If so, there’s no way that pi-hole could tell the plugin to update its status.

**Comment by Damien514** [comment]
Thanks for the quick reply! I disabled pi-hole with my "Home" application, through the switch button. Works very well, and my PiHole stop filtering for a minute, as expected. But I thought it would be great for the buttons to switch back to the original status after the delay. As the dely is defined in the JSON, may be you could do this without getting the status from the Pi-Hole.

**Comment by arendruni** [comment]
Do you mean using a timeout within the plugin?

**Comment by Damien514** [comment]
Ok, forget it. In fact, the plugin is working well :-) Home application does not refresh "live"' the button status. Sorry for bothering, and thank you for this great plugin!
