### ISSUE TITLE
[BUG] Does not work with pihole installed in HTTPS

### ISSUE THREAD

**Issue by eddie209** [arendruni/homebridge-pihole#15]
**Describe the bug**
If the port is set to 443, the plugin does not work (a error 400 is thrown).

I make a workaround with invoking https library instead of http.

**Comment by arendruni** [comment]
Hi @eddie209 thanks for this issue and sorry for the late answer. 
I’m testing the use of https module, if you could install the plugin from the development branch and tell me if it works.
