### ISSUE TITLE
Improve readme to call out what this plugin does and why a homebridge user would want to install it

### ISSUE THREAD

**Issue by karann-msft** [arendruni/homebridge-pihole#18]
I have no clue why this plugin exists and what it does. I know what is pihole and have it running on my pi zero. Ditto for homebridge. Nada for homebridge-pihole.

**Comment by arendruni** [comment]
Hi @karann-msft, I understand the lack of a comprehensive explanation of the plugin, I will try my best to improve the readme.
So, this plugin is a switch that disables Pi-hole making easier to temporarily turn off the blocker.
