### ISSUE TITLE
[request] reverse switch on/off

### ISSUE THREAD

**Issue by acosmichippo** [arendruni/homebridge-pihole#19]
Hello,

Due to the way homekit handles switch on/off i would prefer the pihole to be considered “off” when it is actually on, and “on” when it is off.  So in other words i’d like for the switch to be considered a “pi-hole bypass” switch.

Is it possible to add this as an option in the future?

Thank you!

**Comment by arendruni** [comment]
Hi @acosmichippo, 

Just yesterday I was thinking on a new version of the plugin with a new `reverse` config to reverse the status of the switch. I’ll  try to integrate this new feature.

**Comment by acosmichippo** [comment]
awesome, thanks again!
