### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 | stdout

### ISSUE THREAD

**Issue by coalfield** [arendruni/homebridge-pihole#2]
I am getting the error: 

> SyntaxError: Unexpected token < in JSON at position 0
> at JSON.parse (<anonymous>)
> at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-pihole/index.js:56:59)
> at IncomingMessage.emit (events.js:203:15)
> at endReadableNT (_stream_readable.js:1145:12)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> Got SIGTERM, shutting down Homebridge...

All setup correctly and installed:

>     {
>       "accessory": "Pihole",
>       "name": "Homelab pi-hole",
>       "auth": "<APIKEY>",
>       "host": "192.168.1.x"
>     }
> 

It only shows when I view in the Home app?  Any ideas?

**Comment by jflow** [comment]
Also seeing this just installed and homebridge is crashing

**Comment by arendruni** [comment]
@coalfield, It could be helpful if you could add previous log lines since there’s a [logger](https://github.com/arendruni/homebridge-pihole/blob/50e4808200d2d7159c2e650788ae6dbf5b1e99cb/index.js#L56) just before parsing to JSON the data from the request.
This error may occur when the host is wrong, are you sure that Pihole admin is running on that address?

**Comment by coalfield** [comment]
> @coalfield, It could be helpful if you could add previous log lines since there’s a [logger](https://github.com/arendruni/homebridge-pihole/blob/50e4808200d2d7159c2e650788ae6dbf5b1e99cb/index.js#L56) just before parsing to JSON the data from the request.
> This error may occur when the host is wrong, are you sure that Pihole admin is running on that address?

I didnt see any log prior in the terminal.  Can you point me in the right direction for where I would find the log?  I am pointing to the correct IP, although its worth noting I am running pihole on the same synology nas, although connecting via mcvlan to get a distinct IP from the synology.  I doubt that effects it as I connect to it via this IP always

**Comment by arendruni** [comment]
@coalfield I may have found the solution to the problem. The function `_makeRequest` wasn’t binded to the pihole prototype so when I called [`this.host`](https://github.com/arendruni/homebridge-pihole/blob/50e4808200d2d7159c2e650788ae6dbf5b1e99cb/index.js#L61) it was always _undefined_, resulting in a request permanently directed to _localhost_.
I released a new version of the plugin that addresses this issue, please download this new update and let me know if you still have problems connecting.

**Comment by coalfield** [comment]
> @coalfield I may have found the solution to the problem. The function `_makeRequest()` wasn’t binded to the pihole prototype so when I called [`this.host`](https://github.com/arendruni/homebridge-pihole/blob/50e4808200d2d7159c2e650788ae6dbf5b1e99cb/index.js#L61) it was always _undefined_, resulting in a request permanently directed to _localhost_.
> I released a new version of the plugin that addresses this issue, please download this new update and let me know if you still have problems connecting.

Looks to be a different error now and same as @MED1975 is seeing:


> 2019-11-24 06:38:33	stdout	[37m[11/24/2019, 6:38:33 AM][39m Got SIGTERM, shutting down Homebridge...
> 2019-11-24 06:38:33	stdout	    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)[39m[22m
> 2019-11-24 06:38:33	stdout	[37m[11/24/2019, 6:38:33 AM][39m [1m[31mError: connect EHOSTUNREACH 192.168.1.3:80

**Comment by arendruni** [comment]
That’s a different error to the one @MED1975 mentioned in #1, that is a `ECONNREFUSED` caused by the plugin that tried to connect to localhost instead of the host provided in the config.json. This error it’s an `EHOSTUNREACH` that means that no one is responding to 192.168.1.3.

This doesn’t seem to have anything to do with the plugin itself, you can test this behaviour by making a GET request to `http://192.168.1.120:80/admin/api.php?status` and see if the host responds.

**Comment by coalfield** [comment]
> That’s a different error to the one @MED1975 mentioned in #1, that is a `ECONNREFUSED` caused by the plugin that tried to connect to localhost instead of the host provided in the config.json. This error it’s an `EHOSTUNREACH` that means that no one is responding to 192.168.1.3.
> 
> This doesn’t seem to have anything to do with the plugin itself, you can test this behaviour by making a GET request to `http://192.168.1.3:80/admin/api.php?status` and see if the host responds.

I get:

{"status":"enabled"}

**Comment by arendruni** [comment]
Did you send it from the same machine where Homebridge is installed?

**Comment by coalfield** [comment]
> Did you send it from the same machine where Homebridge is installed?

You are spot on... I could not try from the synology as there is no browser so tried a ping which failed.  Since realised mcvlan is mapping to 192.168.100.x and found the pihole IP.  Amended this and now it works a treat!  Thank you

**Comment by appleimperio** [comment]
I have exactly the same issue pihole running on a macvlan. Im using the ip of the macvlan and from my browser reads {"status":"enabled"} but the plugin does not find it. how did you solved it
