### ISSUE TITLE
[BUG] Hello 

### ISSUE THREAD

**Issue by Alex565rf** [arendruni/homebridge-pihole#22]
Hello thank you for the plugin ! 

I can't get it to work.. 

Than's a lot!
[homebridge.log (1).txt](https://github.com/arendruni/homebridge-pihole/files/5235336/homebridge.log.1.txt)

"accessories": [
        {
            "name": "PUB off",
            "auth": "yICm2Fbh",
            "ssl": false,
            "host": "localhost",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 120,
            "reversed": true,
            "logLevel": 2,
            "accessory": "Pihole"

**Comment by arendruni** [comment]
Hi @Alex565rf and thanks for this issue,

From the log that you attached it seems that the plugin is connecting to a Pi-hole configured to use HTTPS, but the plugin has the `ssl` options set to false. Do you have any customisation to your Pi-hole?
