### ISSUE TITLE
[BUG] can't connect to Pihole

### ISSUE THREAD

**Issue by JustAnotherPU** [arendruni/homebridge-pihole#23]
Hello,

I am trying to connect the plugin to my pihole installation but can't.
Ip and port are standard and working when doing a copy paste to any browser.

Can you please assist ? 

  syscall: 'connect',
  address: '192.168.1.200',
  port: 80,
  config: {
    url: 'api.php',
    method: 'get',
    params: { status: 1 },
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.19.2'
    },
    baseURL: 'http://192.168.1.200:80/admin/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'http:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/admin/api.php?status=1',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.1.200',
      port: '80',
      nativeProtocols: [Object],
      pathname: '/admin/api.php',
      search: '?status=1'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /admin/api.php?status=1 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: 192.168.1.200\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/admin/api.php?status=1',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.1.200:80/admin/api.php?status=1',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}

**Comment by arendruni** [comment]
Hi @JustAnotherPU and thanks for this issue,

How did you configure the plugin?

**Comment by JustAnotherPU** [comment]
like this ,

 {
            "name": "Pihole",
            "auth": "MyauthKey",
            "ssl": false,
            "host": "192.168.1.200",
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": false,
            "logLevel": 2,
            "accessory": "Pihole"
        }

**Comment by JustAnotherPU** [comment]
I think a found the problem, his isn't related to the plugin I run both Homebridge and PiHole in a docker and due to the nature of how containers they are not capable of communicating with each other so the homebridge can't ping Pihole therefore the ip can't be reached that what's causing the error.

Still need to learn how to make them communicate but that is another issue I hope to solve.

**Comment by arendruni** [comment]
OK, I supposed that it wasn’t related to the plugin itself.

I do have both Pi-hole and Homebridge running on Docker, I configured Homebridge container with `network_mode` set to `host`, as explained [here](https://github.com/oznu/docker-homebridge#compatibility), and Pi-hole container to map the admin port 80 to the 3000, in this way the plugin can reach Pi-hole using the host address.
