### ISSUE TITLE
Pi-Hole status does not change from Accessory [BUG]

### ISSUE THREAD

**Issue by msbc42** [arendruni/homebridge-pihole#24]
**Describe the bug**
Turning the PiHole HomeKit Accessory (switch) on has no effect on pihole.

**Expected behavior**
PiHole disabled for configured time - 30s.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] HomeBridge 1.2.3 Docker on Ubuntu

**Additional context**
HomeKit Accessory changes from Off to On (and On to Off) but PiHole Status does not change. PiHole running in Docker on Ubuntu - same host as HomeBridge container. HTTP, no SSL.

**Comment by arendruni** [comment]
Hi @msbc42, could you please add some homebridge logs to this issue? Before doing it make sure to correctly add the `"logLevel": 2` in you config.json file.

**Comment by msbc42** [comment]
Hi @arendruni, I set the logLevel and also enabled Debug mode. Re-started HomeBridge, toggled the piHole switch from the widget in HomeBridge UI. The only lines to ref PiHole in the entire /homebridge/homebridge.log:

`[10/11/2020, 10:59:35 AM] Loaded plugin: homebridge-pihole@0.3.1`
`[10/11/2020, 10:59:35 AM] Registering accessory 'homebridge-pihole.Pihole'`
`[10/11/2020, 10:59:36 AM] [Pihole] Initializing Pihole accessory...`

**Comment by msbc42** [comment]
I realised that I set the logLevel in the wrong place. Re-statrted and now I get additional output in the log:
`[10/11/2020, 1:14:26 PM] Loaded plugin: homebridge-pihole@0.3.1`
`[10/11/2020, 1:14:26 PM] Registering accessory 'homebridge-pihole.Pihole'`
`[10/11/2020, 1:14:26 PM] [Pihole] Initializing Pihole accessory...`
`[10/11/2020, 1:14:36 PM] [Pihole] {"data":{"status":"enabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=rkf40dk0n8c1ccn5sg0uuihse6; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"20","connection":"close","date":"Sun, 11 Oct 2020 02:14:36 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`
`[10/11/2020, 1:14:39 PM] [Pihole] {"data":{"status":"enabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=p8rlsel2q4bfndd6es4v9n3p97; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"20","connection":"close","date":"Sun, 11 Oct 2020 02:14:39 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`
`[10/11/2020, 1:15:04 PM] [Pihole] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=1qt5stljsh4k0o544p8sr1a033; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"21","connection":"close","date":"Sun, 11 Oct 2020 02:15:04 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"disable":30,"auth":"blah-blah-blah-blah"},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`
`[10/11/2020, 1:15:04 PM] [Pihole] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=i1q9p322id5a29ei835act5jb4; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"21","connection":"close","date":"Sun, 11 Oct 2020 02:15:04 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`
`[10/11/2020, 1:15:06 PM] [Pihole] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=tu1bhl54msh446v1qh6elg6iu5; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"21","connection":"close","date":"Sun, 11 Oct 2020 02:15:06 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"status":1},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}`

**Comment by arendruni** [comment]
I think there's nothing wrong on the plugin side since it correctly receives a 200 status:

> [10/11/2020, 1:15:04 PM] [Pihole] {"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","set-cookie":["PHPSESSID=1qt5stljsh4k0o544p8sr1a033; path=/"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","content-length":"21","connection":"close","date":"Sun, 11 Oct 2020 02:15:04 GMT","server":"lighttpd/1.4.45"},"request":{"url":"api.php","method":"get","params":{"disable":30,"auth":"blah-blah-blah-blah"},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"baseURL":"http://192.168.1.32:80/admin/","transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}

How did you configure the plugin?

**Comment by msbc42** [comment]
Seems to be working OK. The 'Status' was not changing in browser (Chrome) but if I refresh the piHole page it does change.

Should the Accessory change back to ON after the configured duration - 30s in my case?

**Comment by arendruni** [comment]
> Should the Accessory change back to ON after the configured duration - 30s in my case?

Since there’s no internal timeout, the plugin's status is fetched from Pi-hole admin every time Homebridge requests an update (for example when you open the Home app), so it will change the its status when an update is requested after Pi-hole is back ON.
