### ISSUE TITLE
[BUG] Homebridge 1.3.0-beta 40

### ISSUE THREAD

**Issue by Damien514** [arendruni/homebridge-pihole#29]
Testing Homebridge 1.3.0-beta 40 and I got this message in my logs:

`Received warning for the plugin 'homebridge-pihole' from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response!
[On@Homebridge 9A0C] SET handler returned write response value, though the characteristic doesn't support write response!`

Anything is working well though.

**Comment by arendruni** [comment]
Hi @Damien514, thanks for this issue!
 I just released a new beta version of the plugin that should fix the warning on Homebridge console, to test it you just need to add `beta` tag to the package name: `npm install homebridge-pihole@beta`. I will wait for your feedback before releasing a the new version.

**Comment by Damien514** [comment]
Seems to be good. Thanks!
