### ISSUE TITLE
Feature Request: Disable Timer

### ISSUE THREAD

**Issue by coalfield** [arendruni/homebridge-pihole#3]
Sorry not sure if this is the place for this, so please direct me to a forum if you have one for this.  Great plugin by the way its great you have put this together.

I wanted to ask if it were possible to consider, now or in the future an update to add a disable timer.  i.e. disable for 30mins as opposed to permanently until its turned back on.  This would be a great new feature and prevent it being forgotten to turn back on.  No issues if its not possible but i thought i would ask, and likewise sorry if this is not the place for it!

**Comment by arendruni** [comment]
Well @coalfield, I just added this feature in the latest [release](https://github.com/arendruni/homebridge-pihole/releases/tag/v0.0.4). In fact, the plugin now supports a new configuration parameter, `time`, that specifies how long pi-hole would be disabled (in seconds).
Make sure to update the package with npm and accordingly add the new parameter to your [`config.json`](https://github.com/arendruni/homebridge-pihole/blob/master/sample-config.json) to use this new feature.
