### ISSUE TITLE
error about gpis pins and device not being a Raspberry Pi

### ISSUE THREAD

**Issue by recoi1er** [arendruni/homebridge-pihole#43]
Hello! I have noticed the plugin has stopped working and in my logs I have:

`10/20/2021, 11:54:16 AM RPi WARNING warning: config.json: hosts[0]: devices[0]: gpio: key missing`

`10/20/2021, 11:54:17 AM RPi WARNING warning: localhost: not a Raspberry Pi`

Device is a Raspberry Pi 4

**Comment by arendruni** [comment]
Hi @recoi1er, could you please add more Homebridge logs? The logs you added doesn’t seem to be related to this plugin.

**Comment by recoi1er** [comment]
getting the same errors still

its working in Home app, but the icon does not restore itself to On when I turn it Off with a 10 second switch back to On but functionally it works

**Comment by arendruni** [comment]
I think that maybe it’s the RPi plugin that is causing the issues.

About the switch that doesn’t automatically reset its status there’s another [issue](https://github.com/arendruni/homebridge-pihole/issues/24) discussing it:

> > Should the Accessory change back to ON after the configured duration - 30s in my case?
> 
> Since there’s no internal timeout, the plugin's status is fetched from Pi-hole admin every time Homebridge requests an update (for example when you open the Home app), so it will change its status when an update is requested after Pi-hole is back ON.

**Comment by arendruni** [comment]
@recoi1er How did you get it working?

**Comment by recoi1er** [comment]
```
10/21/2021, 9:57:07 AMPiHole BridgeConfiguration change
10/21/2021, 9:57:07 AMpiholebridge stopping
10/21/2021, 9:57:13 AMPiHole Bridge starting
10/21/2021, 9:57:16 AMPiHole BridgeLoaded plugin 'homebridge-pihole'
10/21/2021, 9:57:16 AMPiHole BridgeLoading 1 accessories...
10/21/2021, 9:57:16 AMPiHole BridgeBridge is running on port 51836.
10/21/2021, 9:57:17 AMPiHole BridgePiHole{"data":{"status":"enabled"},"status":200,"statusText":"OK","headers":{"set-cookie":["PHPSESSID=00rajd25s6mgooe1nahpjid0di; path=/; HttpOnly"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"20","connection":"close","date":"Thu, 21 Oct 2021 16:57:17 GMT","server":"lighttpd/1.4.59"},"request":{"method":"GET","url":"api.php","params":{"status":1},"baseURL":"http://localhost:1882/admin/","responseType":"json"}}
10/21/2021, 9:57:24 AMPiHole BridgePiHole{"data":{"status":"disabled"},"status":200,"statusText":"OK","headers":{"set-cookie":["PHPSESSID=00lrm8uhcvsvsf6ugljsuudo18; path=/; HttpOnly"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-type":"application/json","x-pi-hole":"The Pi-hole Web interface is working!","x-frame-options":"DENY","content-length":"21","connection":"close","date":"Thu, 21 Oct 2021 16:57:24 GMT","server":"lighttpd/1.4.59"},"request":{"method":"GET","url":"api.php","params":{"disable":60,"auth":"ed9d0caee08cc1bb6133c4091b31c3caec1ef65f4290ebf9ca05d8fb01f2bbf3"},"baseURL":"http://localhost:1882/admin/","responseType":"json"}}
```
