### ISSUE TITLE
[BUG] Homebridge taken offline if Pi-hole is down

### ISSUE THREAD

**Issue by epheterson** [arendruni/homebridge-pihole#45]
**Describe the bug**
I'm doing some work on my NAS which hosts my pi-hole server, and with the pi-hole docker not running I noticed all of my homebridge accessories went offline. When I checked homebridge, it was crashing in a loop. 

I suspected the issue had to do with my NAS being down, and when I changed the IP used for the Pi-hole plugin in homebridge config to something else, homebridge was able to stay online. It seems the server being online, but not responsive causes this issue and using a random non-existant IP does not.

I have logging set to info level, but all I ever see is:
`[12/7/2021, 5:49:15 PM] [Pihole] Initializing Pihole accessory...`

**To Reproduce**
1. Create a pi-hole server running pi-hole in docker
2. Setup Homebridge plugin to have 5 minute off switch for pi-hole (nothing special, no child bridge)
3. Verify pi-hole and homebridge setup work as expected
4. Close docker, keeping the server IP online
5. Check homebridge

**Expected behavior**
Pi-hole plugin should be able to handle communication issues without bringing down Homebridge.

**Desktop (please complete the following information):**
 - OS: macOS 21C5045a running Homebridge v1.3.8
 - Browser: Safari
 - Version: homebridge-pihole v0.3.5

**Comment by epheterson** [comment]
I'm actually still seeing it go down, but it stays up for 30s now and before it would go down immediately.

**Comment by srapari** [comment]
same here. one thing to mention though is that homebridge goes down if the server respond with a connection refused or it is actually unreachable:

[12/29/2021, 9:45:21 AM] [Home - Pi3b  pi-hole - 2 minutes] Error: connect EHOSTUNREACH 192.168.2.14:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.2.14',
  port: 80,
  config: {
    url: 'api.php',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
....
[12/29/2021, 9:45:21 AM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at On.<anonymous> (/usr/lib/node_modules/homebridge-pihole/src/index.ts:100:6)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

or 

[12/29/2021, 9:22:50 AM] [Home - Pi3b  pi-hole - 2 minutes] Error: connect ECONNREFUSED 192.168.2.14:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.2.14',
  port: 80,
  config: {
    url: 'api.php',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },

**Comment by arendruni** [comment]
Hi @epheterson and sorry for the late answer.

I've found the source of this problem and will be fixed in the next release.

**Comment by epheterson** [comment]
Thanks, just updated!
