### ISSUE TITLE
Recent Pihole update broke plugin

### ISSUE THREAD

**Issue by zvarnes** [arendruni/homebridge-pihole#57]
The most recent update breaks the ability to disable/enable pihole through the API.

**Comment by PatriceRobert** [comment]
Hey homebridgers !
Same here, and no logs, will try tu get in debug mode to check.....
No effect at all after upgrading:
`Docker Tag 2022.09.1 Pi-hole v5.12 FTL v5.17 Web Interface v5.14.1
`

-- Patrice.

**Comment by arendruni** [comment]
Hi @zvarnes, @PatriceRobert and thanks for submitting this issue.
I updated my pi-hole instance and I can confirm that the plugin does not work. Last pi-hole update broke all apis calls with `auth=...`, see https://github.com/pi-hole/AdminLTE/issues/2326 for more informations, a fix will be added in their next release.

I am leaving this issue open as a spike.

**Comment by PatriceRobert** [comment]
Thanks for the update @arendruni  a shame as we need to wait a bit which already happened in the past....
That's life.... ;-)

**Comment by arendruni** [comment]
This issue was fixed with pi-hole Web Interface version [5.14.2](https://github.com/pi-hole/AdminLTE/releases/v5.14.2) release. Tested with pi-hole [v5.12.1](https://github.com/pi-hole/pi-hole/releases/v5.12.1), FTL [v5.18](https://github.com/pi-hole/FTL/releases/v5.18) and Web Interface [v5.15](https://github.com/pi-hole/AdminLTE/releases/v5.15)

**Comment by PatriceRobert** [comment]
> This issue was fixed with pi-hole Web Interface version [5.14.2](https://github.com/pi-hole/AdminLTE/releases/v5.14.2) release. Tested with pi-hole [v5.12.1](https://github.com/pi-hole/pi-hole/releases/v5.12.1), FTL [v5.18](https://github.com/pi-hole/FTL/releases/v5.18) and Web Interface [v5.15](https://github.com/pi-hole/AdminLTE/releases/v5.15)

Thanks @arendruni for the heads-up, working also on my side:
`Docker Tag 2022.09.3 Pi-hole v5.12.1 FTL v5.18 Web Interface v5.15`

-- Patrice.
