### ISSUE TITLE
Connectivity broken in HomeKit as of Pi-Hole FTL v5.20 and Web v5.18

### ISSUE THREAD

**Issue by PocketTim** [arendruni/homebridge-pihole#59]
PiHole FTL v5.20 and Web v5.18 have been released with some API changes.

This has broken connectivity with HomeKit (turning Pi-Hole off an on causes no action).

**Comment by TheGITofTeo997** [comment]
I am experiencing a simialr problem. The switch in HomeKit is always OFF (even though Pi-Hole is ON). If I do an on-off cycle it works for a little bit and then it shuts off again.
Same version of Pi-Hole

**Comment by marcothuemmler** [comment]
Seems to be fixed in latest beta (v0.4.2-beta.2). Thanks @arendruni for the quick response!

**Comment by arendruni** [comment]
I've just released a beta version (v0.4.2-beta.3) that should fix the status api (which now requires the `auth` param). Seems to be fixed on my side too, @TheGITofTeo997 Could you give it a try?

**Comment by TheGITofTeo997** [comment]
> I've just released a beta version (v0.4.2-beta.3) that should fix the status api (which now requires the `auth` param). Seems to be fixed on my side too, @TheGITofTeo997 Could you give it a try?

I am currently running Homebridge via docker, I am pretty new to it so is there a way I can update this plugin to the new release via UI or via another method? 
I will try as soon as possible after the update, thanks

**Comment by arendruni** [comment]
OK, from the Homebridge config UI navigate through the plugins page, click on the tool icon (second from the right) on the homebridge-pihole plugin panel and select "Install Alternate Version" then select v0.4.2-beta.3 from the prompt.

**Comment by TheGITofTeo997** [comment]
> OK, from the Homebridge config UI navigate through the plugins page, click on the tool icon (second from the right) on the homebridge-pihole plugin panel and select "Install Alternate Version" then select v0.4.2-beta.3 from the prompt.

Thanks for telling me how to upgrade. I upgrade the plugin and looks like it is working perfectly, I would say this is solved.
Happy Xmas!

**Comment by arendruni** [comment]
Fixed with latest release [v.0.4.2](https://github.com/arendruni/homebridge-pihole/releases/tag/v0.4.2)
