### ISSUE TITLE
After Upgrade from 0.0.5 -> 0.08 Homebrige becomes unresponsive

### ISSUE THREAD

**Issue by WRTHacker** [arendruni/homebridge-pihole#9]
Homebridge (nodejs 12.14.1, npm 6.16.6) runs very stable.
No Problems with latest UI X 4.9.0

Up to now with Piholke v0.0.5 no problems.

Upgrade to 0.0.8 and restart Homebridge -> Homebridge on the GUI seems to be o.k.
However, all devices in Homekit becomes unresponsive.
The plugin reports an error:

Feb  2 17:27:19 hb homebridge[1294]: [2/2/2020, 5:27:19 PM] [Pihole1 10 min. aus] Error: socket hang up
Feb  2 17:27:19 hb homebridge[1294]:     at connResetException (internal/errors.js:570:14)
Feb  2 17:27:19 hb homebridge[1294]:     at Socket.socketOnEnd (_http_client.js:440:23)
Feb  2 17:27:19 hb homebridge[1294]:     at Socket.emit (events.js:228:7)
Feb  2 17:27:19 hb homebridge[1294]:     at endReadableNT (_stream_readable.js:1185:12)
Feb  2 17:27:19 hb homebridge[1294]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Feb  2 17:27:19 hb homebridge[1294]:   code: 'ECONNRESET'
Feb  2 17:27:19 hb homebridge[1294]: }

https connect works great, checked with wget

**Comment by WRTHacker** [comment]
... if I roll back the plugin, the error persits!
Have to restore the server ...

**Comment by arendruni** [comment]
Hi @WRTHacker, thanks for this issue.

Does the error persist without the plugin installed?

**Comment by WRTHacker** [comment]
Yes it does

**Comment by arendruni** [comment]
How do you configured the plugin?

**Comment by WRTHacker** [comment]
Here is the error:
 [2/2/2020, 7:04:45 PM] Error: The requested accessory 'Pihole' was not registered by any plugin.
Feb  2 19:04:45 hb homebridge[4426]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
Feb  2 19:04:45 hb homebridge[4426]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
Feb  2 19:04:45 hb homebridge[4426]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
Feb  2 19:04:45 hb homebridge[4426]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Feb  2 19:04:45 hb homebridge[4426]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Feb  2 19:04:45 hb homebridge[4426]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
Feb  2 19:04:45 hb homebridge[4426]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
Feb  2 19:04:45 hb homebridge[4426]:     at Module.load (internal/modules/cjs/loader.js:811:32)
Feb  2 19:04:45 hb homebridge[4426]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
Feb  2 19:04:45 hb homebridge[4426]:     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
Feb  2 19:04:45 hb homebridge[4426]: [2/2/2020, 7:04:45 PM] [MagicHome-Platform] Getting Bulbs from Cache
Feb  2 19:04:46 hb homebridge[4426]: [2/2/2020, 7:04:46 PM] Got SIGTERM, shutting down Homebridge...

**Comment by arendruni** [comment]
Have you tried installing it again with `npm install -g homebridge-pihole@latest`?

**Comment by WRTHacker** [comment]
Config:
 {
            "accessory": "Pihole",
            "name": "Pihole1 10 min. aus",
            "auth": "the token",
            "host": "192.168.X.YZ",
            "port": "443",
            "time": 600
        },
        {
            "accessory": "Pihole",
            "name": "Pihole2 10 min. aus",
            "auth": "the auth token",
            "host": "192.168.X.ab",
            "port": "443",
            "time": 600
        },

**Comment by WRTHacker** [comment]
Yes, just tried: stop homebridge uninstall plugin; install, start homebridge

Unresponive, when I update the device status in home+ App the error occured:


Feb  2 19:12:06 hb homebridge[442]: [2/2/2020, 7:12:06 PM] [Pihole1 10 min. aus] Error: socket hang up
Feb  2 19:12:06 hb homebridge[442]:     at connResetException (internal/errors.js:570:14)
Feb  2 19:12:06 hb homebridge[442]:     at Socket.socketOnEnd (_http_client.js:440:23)
Feb  2 19:12:06 hb homebridge[442]:     at Socket.emit (events.js:228:7)
Feb  2 19:12:06 hb homebridge[442]:     at endReadableNT (_stream_readable.js:1185:12)
Feb  2 19:12:06 hb homebridge[442]:     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Feb  2 19:12:06 hb homebridge[442]:   code: 'ECONNRESET'
Feb  2 19:12:06 hb homebridge[442]: }

**Comment by arendruni** [comment]
Have you tried using port 80?

**Comment by WRTHacker** [comment]
No, no service is accessible via port 80. To check, I have to reconfigure too much. Service, fireall, iptables ...

**Comment by arendruni** [comment]
> Homebridge (nodejs 12.14.1, npm 6.16.6) runs very stable.
> No Problems with latest UI X 4.9.0
> 
> Up to now with Piholke v0.0.5 no problems.
> 
> Upgrade to 0.0.8 and restart Homebridge -> Homebridge on the GUI seems to be o.k.
> However, all devices in Homekit becomes unresponsive.
> The plugin reports an error:
> 
> Feb 2 17:27:19 hb homebridge[1294]: [2/2/2020, 5:27:19 PM] [Pihole1 10 min. aus] Error: socket hang up
> Feb 2 17:27:19 hb homebridge[1294]: at connResetException (internal/errors.js:570:14)
> Feb 2 17:27:19 hb homebridge[1294]: at Socket.socketOnEnd (_http_client.js:440:23)
> Feb 2 17:27:19 hb homebridge[1294]: at Socket.emit (events.js:228:7)
> Feb 2 17:27:19 hb homebridge[1294]: at endReadableNT (_stream_readable.js:1185:12)
> Feb 2 17:27:19 hb homebridge[1294]: at processTicksAndRejections (internal/process/task_queues.js:81:21) {
> Feb 2 17:27:19 hb homebridge[1294]: code: 'ECONNRESET'
> Feb 2 17:27:19 hb homebridge[1294]: }
> 
> https connect works great, checked with wget

When testing with wget, did you make the request from the same server where Homebridge is running?

**Comment by arendruni** [comment]
I could replicate the same error by changing the port from 80 to 443
```
[2/2/2020, 9:45:41 PM] [Pi-hole-debug] Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ECONNRESET'
}
```
This seams reasonable since pi-hole uses port 443 as a sinkhole for ads that use SSL.

**Comment by WRTHacker** [comment]
Hmm, newer versions didn't listen on port 443 ... and there are a lot of recepies in the net how to enable admin gui with certificate on port 443.

**Comment by WRTHacker** [comment]
To make it more clear: My Piholes are in an "server" VLAN. DNS, DHCP and https is allowed. On https the Admin GUI and so the API is running.

**Comment by arendruni** [comment]
What is the last version of the plugin that works with your configuration?

**Comment by WRTHacker** [comment]
That was the 0.0.5 a previous update to 0.0.7 has had the same problem.

**Comment by arendruni** [comment]
> ... if I roll back the plugin, the error persits!
> Have to restore the server ...

So, right now you are running the version 0.0.5?

**Comment by WRTHacker** [comment]
Yes.

**Comment by arendruni** [comment]
Does it work with the 0.0.6 version?

**Comment by WRTHacker** [comment]
Don't know, I leave that version out. Is it important to test?

**Comment by arendruni** [comment]
It could be helpful to find what causes of the problem.

**Comment by WRTHacker** [comment]
Yes, same error with 0.0.6

**Comment by WRTHacker** [comment]
Hi arendruni, did you get any idea concerning the issue?
Best regards

**Comment by arendruni** [comment]
@WRTHacker Sorry for the late answer, but I still don’t know what is causing the bug. 

I will really appreciate it if you could clone the repository and start Homebridge in debug mode with just this plugin installed, I’d try changing to `require("https")` at line 2 the and see if the error persists.

**Comment by WRTHacker** [comment]
Sorry, I need some advice/support and fear, that my whole HomeKit automation an scenes with Homebridge device in it than vanishes.

**Comment by arendruni** [comment]
Okay, to help you going through this I created a new branch called patch-1, to test this new "version" run `npm install --save git+https://github.com/arendruni/homebridge-pihole.git#patch-1` or edit it directly in your package.json

**Comment by WRTHacker** [comment]
Sorry for the delay, but I get an error when try to install:

root@hb:~# npm install --save git+https://github.com/arendruni/homebridge-pihole.git#patch-1
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/arendruni/homebridge-pihole.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-23T15_12_39_250Z-debug.log

**Comment by arendruni** [comment]
It seems that you don’t have git installed on your machine, to avoid installing it, you could try by installing the test package directly from a tarball by running `npm install --save https://github.com/arendruni/homebridge-pihole/archive/patch-1.tar.gz`

**Comment by WRTHacker** [comment]
root@hb:~# npm install --save https://github.com/arendruni/homebridge-pihole/archive/patch-1.tar.gz
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ homebridge-pihole@0.0.8
added 1 package from 1 contributor and audited 1 package in 2.179s
found 0 vulnerabilities

root@hb:~# time npm list -g --depth=0
/usr/lib
+-- homebridge@0.4.50
+-- homebridge-automation-switches@3.2.1
+-- homebridge-config-ui-x@4.10.0
+-- homebridge-daily-sensors@0.5.3-alpha.24
+-- homebridge-delay-switch@2.1.0
+-- homebridge-dummy@0.4.1
+-- homebridge-magichome-platform@1.4.0
+-- homebridge-occupancy-delay@1.0.1
+-- homebridge-pihole@0.0.5
+-- homebridge-shelly@0.11.0
+-- homebridge-unifi-occupancy-sensor@1.0.0
+-- homebridge-weather-plus@3.0.4
`-- npm@6.13.7

**Comment by WRTHacker** [comment]
Nothing has changed in die plugin dir /usr/lib/node_modules.

**Comment by arendruni** [comment]
Try again by installing the plugin globally by `npm install -g https://github.com/arendruni/homebridge-pihole/archive/patch-1.tar.gz`

**Comment by WRTHacker** [comment]
[2/25/2020, 7:57:15 PM] [Pihole1 10 min. aus] Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

### I use self signed certificates of my own ca

**Comment by arendruni** [comment]
I’m sorry but I can’t help you fix this issue, I suggest you to revert the plugin back to the last working version.

**Comment by WRTHacker** [comment]
Many thanks for the help, even the problem is not fixed.

**Comment by arendruni** [comment]
Hey @WRTHacker, in the latest version of the plugin we added https support, have you tried installing it?

**Comment by WRTHacker** [comment]
Hi arendruni,
runs like a charm. Great work. Thanks for the ping :-)
Could be closed as resolved.
Regards

**Comment by WRTHacker** [comment]
Stop, after a restart after GUI Update pihole Plugin failed!

Self signed certificates in my infrastructure. Set NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' for this. Don't know how ot insert my own ca cert:


Jun 11 15:01:00 hb homebridge[4709]: [6/11/2020, 3:01:00 PM] [Pihole2 10 min. aus] Error: unable to verify the first certificate
Jun 11 15:01:00 hb homebridge[4709]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
Jun 11 15:01:00 hb homebridge[4709]:     at TLSSocket.emit (events.js:310:20)
Jun 11 15:01:00 hb homebridge[4709]:     at TLSSocket._finishInit (_tls_wrap.js:917:8)
Jun 11 15:01:00 hb homebridge[4709]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
Jun 11 15:01:00 hb homebridge[4709]:   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
Jun 11 15:01:00 hb homebridge[4709]:   config: {
Jun 11 15:01:00 hb homebridge[4709]:     url: 'api.php',
Jun 11 15:01:00 hb homebridge[4709]:     method: 'get',
Jun 11 15:01:00 hb homebridge[4709]:     params: { status: 1 },
Jun 11 15:01:00 hb homebridge[4709]:     headers: {
Jun 11 15:01:00 hb homebridge[4709]:       Accept: 'application/json, text/plain, */*',
Jun 11 15:01:00 hb homebridge[4709]:       'User-Agent': 'axios/0.19.2'
Jun 11 15:01:00 hb homebridge[4709]:     },
Jun 11 15:01:00 hb homebridge[4709]:     baseURL: 'https://192.168.1.56:443/admin/',
Jun 11 15:01:00 hb homebridge[4709]:     transformRequest: [ [Function: transformRequest] ],
Jun 11 15:01:00 hb homebridge[4709]:     transformResponse: [ [Function: transformResponse] ],
Jun 11 15:01:00 hb homebridge[4709]:     timeout: 0,
Jun 11 15:01:00 hb homebridge[4709]:     adapter: [Function: httpAdapter],
Jun 11 15:01:00 hb homebridge[4709]:     responseType: 'json',
Jun 11 15:01:00 hb homebridge[4709]:     xsrfCookieName: 'XSRF-TOKEN',
Jun 11 15:01:00 hb homebridge[4709]:     xsrfHeaderName: 'X-XSRF-TOKEN',
Jun 11 15:01:00 hb homebridge[4709]:     maxContentLength: -1,
Jun 11 15:01:00 hb homebridge[4709]:     validateStatus: [Function: validateStatus],
Jun 11 15:01:00 hb homebridge[4709]:     data: undefined
Jun 11 15:01:00 hb homebridge[4709]:   },
Jun 11 15:01:00 hb homebridge[4709]:   request: Writable {
Jun 11 15:01:00 hb homebridge[4709]:     _writableState: WritableState {
Jun 11 15:01:00 hb homebridge[4709]:       objectMode: false,
Jun 11 15:01:00 hb homebridge[4709]:       highWaterMark: 16384,
Jun 11 15:01:00 hb homebridge[4709]:       finalCalled: false,
Jun 11 15:01:00 hb homebridge[4709]:       needDrain: false,
Jun 11 15:01:00 hb homebridge[4709]:       ending: false,
Jun 11 15:01:00 hb homebridge[4709]:       ended: false,
Jun 11 15:01:00 hb homebridge[4709]:       finished: false,
Jun 11 15:01:00 hb homebridge[4709]:       destroyed: false,
Jun 11 15:01:00 hb homebridge[4709]:       decodeStrings: true,
Jun 11 15:01:00 hb homebridge[4709]:       defaultEncoding: 'utf8',
Jun 11 15:01:00 hb homebridge[4709]:       length: 0,
Jun 11 15:01:00 hb homebridge[4709]:       writing: false,
Jun 11 15:01:00 hb homebridge[4709]:       corked: 0,
Jun 11 15:01:00 hb homebridge[4709]:       sync: true,
Jun 11 15:01:00 hb homebridge[4709]:       bufferProcessing: false,
Jun 11 15:01:00 hb homebridge[4709]:       onwrite: [Function: bound onwrite],
Jun 11 15:01:00 hb homebridge[4709]:       writecb: null,
Jun 11 15:01:00 hb homebridge[4709]:       writelen: 0,
Jun 11 15:01:00 hb homebridge[4709]:       afterWriteTickInfo: null,
Jun 11 15:01:00 hb homebridge[4709]:       bufferedRequest: null,
Jun 11 15:01:00 hb homebridge[4709]:       lastBufferedRequest: null,
Jun 11 15:01:00 hb homebridge[4709]:       pendingcb: 0,
Jun 11 15:01:00 hb homebridge[4709]:       prefinished: false,
Jun 11 15:01:00 hb homebridge[4709]:       errorEmitted: false,
Jun 11 15:01:00 hb homebridge[4709]:       emitClose: true,
Jun 11 15:01:00 hb homebridge[4709]:       autoDestroy: false,
Jun 11 15:01:00 hb homebridge[4709]:       bufferedRequestCount: 0,
Jun 11 15:01:00 hb homebridge[4709]:       corkedRequestsFree: [Object]
Jun 11 15:01:00 hb homebridge[4709]:     },
Jun 11 15:01:00 hb homebridge[4709]:     writable: true,
Jun 11 15:01:00 hb homebridge[4709]:     _events: [Object: null prototype] {
Jun 11 15:01:00 hb homebridge[4709]:       response: [Function: handleResponse],
Jun 11 15:01:00 hb homebridge[4709]:       error: [Function: handleRequestError]
Jun 11 15:01:00 hb homebridge[4709]:     },
Jun 11 15:01:00 hb homebridge[4709]:     _eventsCount: 2,
Jun 11 15:01:00 hb homebridge[4709]:     _maxListeners: undefined,
Jun 11 15:01:00 hb homebridge[4709]:     _options: {
Jun 11 15:01:00 hb homebridge[4709]:       protocol: 'https:',
Jun 11 15:01:00 hb homebridge[4709]:       maxRedirects: 21,
Jun 11 15:01:00 hb homebridge[4709]:       maxBodyLength: 10485760,
Jun 11 15:01:00 hb homebridge[4709]:       path: '/admin/api.php?status=1',
Jun 11 15:01:00 hb homebridge[4709]:       method: 'GET',
Jun 11 15:01:00 hb homebridge[4709]:       headers: [Object],
Jun 11 15:01:00 hb homebridge[4709]:       agent: undefined,
Jun 11 15:01:00 hb homebridge[4709]:       agents: [Object],
Jun 11 15:01:00 hb homebridge[4709]:       auth: undefined,
Jun 11 15:01:00 hb homebridge[4709]:       hostname: '192.168.1.56',
Jun 11 15:01:00 hb homebridge[4709]:       port: '443',
Jun 11 15:01:00 hb homebridge[4709]:       nativeProtocols: [Object],
Jun 11 15:01:00 hb homebridge[4709]:       pathname: '/admin/api.php',
Jun 11 15:01:00 hb homebridge[4709]:       search: '?status=1'
Jun 11 15:01:00 hb homebridge[4709]:     },
Jun 11 15:01:00 hb homebridge[4709]:     _redirectCount: 0,
Jun 11 15:01:00 hb homebridge[4709]:     _redirects: [],
Jun 11 15:01:00 hb homebridge[4709]:     _requestBodyLength: 0,
Jun 11 15:01:00 hb homebridge[4709]:     _requestBodyBuffers: [],
Jun 11 15:01:00 hb homebridge[4709]:     _onNativeResponse: [Function],
Jun 11 15:01:00 hb homebridge[4709]:     _currentRequest: ClientRequest {
Jun 11 15:01:00 hb homebridge[4709]:       _events: [Object: null prototype],
Jun 11 15:01:00 hb homebridge[4709]:       _eventsCount: 6,
Jun 11 15:01:00 hb homebridge[4709]:       _maxListeners: undefined,
Jun 11 15:01:00 hb homebridge[4709]:       outputData: [],
Jun 11 15:01:00 hb homebridge[4709]:       outputSize: 0,
Jun 11 15:01:00 hb homebridge[4709]:       writable: true,
Jun 11 15:01:00 hb homebridge[4709]:       _last: true,
Jun 11 15:01:00 hb homebridge[4709]:       chunkedEncoding: false,

**Comment by WRTHacker** [comment]
Now I have addes my own ca cert ...

systemctl edit homebridge

[Service]
Environment="NODE_EXTRA_CA_CERTS=/var/lib/homebridge/ssl/ca.koellers.net.crt"

But now ... will set the TLS

A switch in the config like for the unifi ocupancy plugin would be nice.

Jun 11 15:33:02 hb homebridge[7381]: [6/11/2020, 3:33:02 PM] [Pihole2 10 min. aus] Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: 192.168.1.56 is not in the cert's list:

Why for ever shold the alternate IP set in the cert list. I never see such an error have > 20 certs running in various VM.

**Comment by WRTHacker** [comment]
This fixes it:

systemctl edit homebridge

[Service]
Environment="NODE_EXTRA_CA_CERTS=/var/lib/homebridge/ssl/ca.koellers.net.crt"
Environment="NODE_TLS_REJECT_UNAUTHORIZED=0"

**Comment by WRTHacker** [comment]
This fixes it not really, the extra ca file didn't help, only the second line. Sorry nodejs is bulls....

systemctl edit homebridge

[Service]
Environment="NODE_EXTRA_CA_CERTS=/var/lib/homebridge/ssl/ca.koellers.net.crt"
Environment="NODE_TLS_REJECT_UNAUTHORIZED=0"
